# Generated by Django 4.2.6 on 2023-10-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Количество продуктов')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('in_order', models.BooleanField(default=False, verbose_name='Заказан')),
                ('for_anonymous_user', models.BooleanField(default=False, verbose_name='От анонимного покупателя')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': ' Категории',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cansel', 'Отмена'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов')], default='in_progress', max_length=100, verbose_name='Статус заказ')),
                ('buying_type', models.CharField(choices=[('self', 'В столовой'), ('delivery', 'Доставить на рабочее место')], default='self', max_length=100, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('products_information', models.TextField(blank=True, null=True, verbose_name='Информация о товарах')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата получения заказа')),
                ('order_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата получения заказа')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Корзина')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='mainapp.employee', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': '    Заказ',
                'verbose_name_plural': '         Заказы',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='mainapp.order', verbose_name='Заказы покупателя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Изображение 4')),
                ('vegan', models.BooleanField(default=False, verbose_name='Веган-блюдо')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Вес')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Калории')),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Белки')),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Жиры')),
                ('carb', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Углеводы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='CartDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID товара')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество единиц товара')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('glist', models.TextField(default='', verbose_name='Параметры')),
                ('in_order', models.BooleanField(default=False, verbose_name='В заказе')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='mainapp.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Пренадлежность к категориям')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': 'Продукты в корзине',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.cartdish', verbose_name='Продукты'),
        ),
    ]
