# Generated by Django 4.2.6 on 2023-10-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_cartdish_content_type_alter_dish_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdish',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.dish', verbose_name='Блюдо'),
        ),
    ]
